#!/usr/bin/env perl
use FindBin;
use lib "$FindBin::Bin/../.meta";
use Dotfiles qw( :ALL );


my $HERE = dir(__FILE__);

gprint "Linking xterm config";
symlink "$HERE/Xresources.conf", "$HOME/.Xresources.d/xterm.conf";
