#!/usr/bin/env -S perl ${HOME}/.dotfiles/install --file

[symlink]
elogind-hibernate.sh: ~/.local/bin/hibernate
elogind-poweroff.sh: ~/.local/bin/poweroff
elogind-reboot.sh: ~/.local/bin/reboot
elogind-suspend.sh: ~/.local/bin/suspend

[run]
# Installing packages
sudo xbps-install -Sy
    awesome
    emacs-gtk3
    epiphany
    elogind
    fish-shell
    i3lock
    light
    m4
    nemo
    redshift
    rofi
    tmux
    vim
    xmodmap
    xrdb
    xterm
# Allowing all users to control backlight
sudo chmod +s /bin/light
# Setting up elogind
bash setup-elogind.sh
