#!/usr/bin/env bash
set -e

# check force
ARGV=()
FORCE=false
for ARG in $@; do
    if [[ $ARG == "-f" ]]; then FORCE=true;
    else ARGV+=" $ARG"; fi
    shift
done

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROFILES_DIR="${BASE_DIR}/.profiles"

function detect_distro { cat /etc/*release | sed -n "s/^NAME=//p" | sed "s/\"//g"; }
function is_xorg_running {
        set +e
        (xset q >/dev/null 2>/dev/null)
        XORG_RUNNING=$?
        set -e
        if [ $XORG_RUNNING -eq 0 ]; then true; else false; fi
}

function install_config {
    echo "Configuring $1"
    pushd $1
    if $FORCE; then
        make install --always-make
    else
        make install
    fi
    popd
}
function install_configs { for config in $@; do install_config $config; done; }
function install_profile {
    for config in `cat "${PROFILES_DIR}/$1"`; do
        install_config $config
    done
}
function install_profiles { for profile in $@; do install_profile $profile; done; }

# checkout submodules
cd $BASE_DIR
git submodule update --init --recursive

if [ ${#ARGV} -eq 0 ]; then
    # automatically detect profiles to install
    PROFILES=()
    SYSTEM=$(uname)
    if [[ $SYSTEM == Linux ]]; then
        PROFILES+=("linux")
        PROFILES+=(`detect_distro`)
        if (is_xorg_running); then
            PROFILES+=("xorg")
        fi
    else
        echo $SYSTEM not supported!
        exit 1
    fi

    install_profiles ${PROFILES[@]}
else
    install_configs $ARGV
fi
