#!/usr/bin/env bash
set -e

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROFILES_DIR="${BASE_DIR}/.meta/profiles"

function detect_distro { cat /etc/*release | sed -n "s/^NAME=//p" | sed "s/\"//g"; }
function is_xorg_running {
        (xset q >/dev/null 2>/dev/null)
        XORG_RUNNING=$?
        if [ $XORG_RUNNING -eq 0 ]; then true; else false; fi
}

function install_config {
    echo "Configuring $1"
    pushd $1 >/dev/null 
    perl ${BASE_DIR}/.meta/install.pl --exec install
    popd >/dev/null 
}
function install_configs { for config in $@; do install_config $config; done; }
function install_profile {
    for config in `cat "${PROFILES_DIR}/$1"`; do
        install_config $config
    done
}
function install_profiles { for profile in $@; do install_profile $profile; done; }

# checkout submodules
cd $BASE_DIR
git submodule update --init --recursive

ARGV=$@
if [ ${#ARGV} -eq 0 ]; then
    # automatically detect profiles to install
    PROFILES=()
    SYSTEM=$(uname)
    if [[ $SYSTEM == Linux ]]; then
        PROFILES+=("linux")
        PROFILES+=(`detect_distro`)
        if (is_xorg_running); then
            PROFILES+=("xorg")
        fi
    else
        echo $SYSTEM not supported!
        exit 1
    fi

    install_profiles ${PROFILES[@]}
else
    install_configs $ARGV
fi
