#!/usr/bin/env perl
use FindBin;
use lib "$FindBin::Bin/../.meta";
use Dotfiles qw( :ALL );

my $HERE = dir(__FILE__);


gprint "Linking vim config";
symlink "$HERE/vimrc", "$HOME/.vimrc";

gprint "Linking vim config dir";
symlink "$HERE/vim", "$HOME/.vim";

gprint "Installing vim plugins"; 
system "vim +PlugInstall +qall";
