#!/usr/bin/env -S perl ${HOME}/.dotfiles/.meta/install.pl --exec

[symlink]
./Xresources.conf: ~/.Xresources.d/rofi.conf

[run]
mkdir -p ~/.config/rofi    

[symlink]
./theme.rasi: ~/.config/rofi/theme.rasi
