#!/usr/bin/env perl
use FindBin;
use lib "$FindBin::Bin/../.meta";
use Dotfiles qw( :ALL );


gprint "Installing packages";
my @packages = qw(

    awesome
    emacs25
    fish
    redshift
    rofi
    slock
    tmux
    uswsusp
    vim
    xclip
    xterm

);
my $packages = join(" ", @packages);
ex "sudo apt install -y $packages";

gprint "Allowing everyone to suspend to ram";
ex "sudo chmod +s /usr/sbin/s2ram";
