#!/usr/bin/env -S perl ${HOME}/.dotfiles/install --file

[run]
# Installing packages
sudo apt install -y
     adwaita-icon-theme-full
     autorandr
     awesome
     emacs
     fish
     nemo
     redshift
     rofi
     slock
     tmux
     uswsusp
     vim
     xclip
     xterm

# Allowing everyone to suspend to ram
sudo chmod +s /usr/sbin/s2ram
