#!/usr/bin/env -S perl ${HOME}/.dotfiles/install --file

[run]
# Installing packages
sudo apt install -y
     adwaita-icon-theme-full
     autorandr
     awesome
     emacs
     fish
     kitty
     moreutils
     nemo
     neovim
     playerctl
     redshift
     rofi
     tmux
     tmuxinator
     uswsusp
     vim
     xclip
		 xsecurelock
     xss-lock
     xterm

# Allowing everyone to suspend to ram
sudo chmod +s /usr/sbin/s2ram

# Warning about required manual actions
echo "Please also install xidlehook: https://gitlab.com/jD91mZM2/xidlehook"

