#!/usr/bin/env perl

use File::Basename 'dirname';
use Cwd 'realpath';
use Term::ANSIColor qw(:constants);

sub gprint {
    print GREEN, @_, RESET, "\n";
}

my $thisdir = dirname(realpath(__FILE__));
my $HOME = $ENV{"HOME"};


gprint "Linking fonts dir";
symlink $thisdir, "$HOME/.fonts";