#!/usr/bin/env perl
use FindBin;
use lib "$FindBin::Bin/../.meta";
use Dotfiles qw( :ALL );

my $HERE = dir(__FILE__);


gprint "Linking gtk2 config";
symlink "$HERE/gtkrc-2.0", "$HOME/.gtkrc-2.0";

gprint "Linking gtk3 config";
symlink "$HERE/gtk3-settings.ini", "$HOME/.config/gtk-3.0/settings.ini";
