#!/usr/bin/env -S perl ${HOME}/.dotfiles/install --file

[run]
# Installing packages
sudo pacman -Sy
	dunst
	feh
	git-delta
	neovim
	picom
	playerctl
	polybar
	redshift
	rofi
	touchegg
	xmonad
	xsecurelock
yay -Sy
	lux
	xidlehook

