#!/usr/bin/env -S perl ${HOME}/.dotfiles/install --file

[run]
# Installing packages
sudo pacman -Sy
	dunst
	feh
	git-delta
	i3lock
	neovim
	picom
	polybar
	redshift
	rofi
	touchegg
	xmonad
yay -Sy
	lux

