#!/usr/bin/env -S perl ${HOME}/.dotfiles/install --file

[run]
# Creating gpg directory
mkdir -p ~/.gnupg
chmod 700 ~/.gnupg

[symlink]
gpg-agent.conf: ~/.gnupg/gpg-agent.conf
scdaemon.conf:  ~/.gnupg/scdaemon.conf
