#!/bin/bash

source ~/.dotfiles/common.sh

#-----------------------------

info "Creating gpg directory"
mkdir -p ~/.gnupg
chmod 700 ~/.gnupg

info "Creating gpg symlinks"
ensure_symlink gpg-agent.conf ~/.gnupg/gpg-agent.conf
ensure_symlink scdaemon.conf  ~/.gnupg/scdaemon.conf
