resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/25.yaml

packages: 
  - .

extra-deps: []

nix:
  enable: true
  packages: 
    - xorg.libX11
    - xorg.libXrandr
    - xorg.libXScrnSaver
    - xorg.libXext
    - xorg.libXft
    - xorg.libXdmcp
    - pkg-config
    - expat

