#!/bin/bash

function exec-if-exists {
    COMMAND=$1
    ARGS="${@:2}"
    if [ -x "$(command -v $COMMAND)" ]; then
        $COMMAND $ARGS
    fi
}

function create-user-dirs {
    DIRS="
        $HOME/doc/desktop
        $HOME/doc/docs
        $HOME/doc/images
        $HOME/doc/music
        $HOME/doc/shared
        $HOME/doc/videos
        $HOME/src
        $HOME/.templates
        $HOME/tmp
    "
    for DIR in $DIRS; do
        mkdir -p $DIR
    done

    exec-if-exists xdg-user-dirs-update
    exec-if-exists xdg-user-dirs-gtk-update
}

create-user-dirs
