#!/usr/bin/env perl
use FindBin;
use lib "$FindBin::Bin/../.meta";
use Dotfiles qw( :ALL );

my $HERE = dir(__FILE__);


gprint "Linking user-dirs";
symlink "$HERE/user-dirs", "$HOME/.config/user-dirs.dirs";

gprint "Linking wallpaper";
symlink "$HERE/wallpaper.png", "$HOME/.config/wallpaper";

gprint "Linking .xinitrc";
symlink "$HERE/xinitrc", "$HOME/.xinitrc";

gprint "Linking Xresources";
symlink "$HERE/Xresources", "$HOME/.Xresources";

gprint "Creating userdirs";
system "./create-user-dirs";

gprint "Creating Xresources config dir";
system "mkdir -p $HOME/.Xresources.d";

gprint "Loading Xresources config";
system "xrdb -I$HOME -load $HOME/.Xresources";
