#!/usr/bin/env -S perl ${HOME}/.dotfiles/.meta/install.pl --exec

[symlink]
./user-dirs: ~/.config/user-dirs.dirs
./wallpaper.png: ~/.config/wallpaper
./xinitrc: ~/.xinitrc
./Xresources: ~/.Xresources

[run]
# Creating userdirs
./create-user-dirs
# Creating Xresources config dir
mkdir -p ~/.Xresources.d
# Loading XResources config
xrdb -I$HOME -load ~/.Xresources
