#!/bin/bash

export PATH=~/.local/bin:$PATH

xrdb -I"$HOME" -load ~/.Xresources -cpp m4

# set keyring variables
if command -v gpgconf &> /dev/null; then
	export GPG_TTY="$(tty)"
	export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
	gpgconf --launch gpg-agent
elif [ -n "$DESKTOP_SESSION" ];then
    #eval $(gnome-keyring-daemon --start)
    export SSH_AUTH_SOCK
fi

# use slock for locking screen
xss-lock i3lock -- -c 000000 &

setxkbmap pl
setxkbmap -option shift:both_capslock
setxkbmap -option caps:ctrl_modifier
xmodmap ~/.xmodmap

# startup applications
redshift -l 42.65:18.1 &
nm-applet &

source ~/.xinitrc.local
