#!/bin/bash

xrdb -I"$HOME" -load ~/.Xresources -cpp m4

# set keyring variables
if [ -n "$DESKTOP_SESSION" ];then
    eval $(gnome-keyring-daemon --start)
    export SSH_AUTH_SOCK
fi

setxkbmap pl
setxkbmap -option shift:both_capslock
setxkbmap -option caps:ctrl_modifier
xmodmap ~/.xmodmap

# startup applications
redshift &
nm-applet &

source ~/.xinitrc.local
