#!/usr/bin/env -S perl ${HOME}/.dotfiles/install --file

[symlink]
./settings.json: ~/.config/VSCodium/User/settings.json
./keybindings.json: ~/.config/VSCodium/User/keybindings.json

[run]
# Installing vscodium extensions
codium --install-extension kahole.magit
codium --install-extension elmtooling.elm-ls-vscode
codium --install-extension sainnhe.gruvbox-material
codium --install-extension jdinhlife.gruvbox
codium --install-extension haskell.haskell
codium --install-extension k--kato.intellij-idea-keybindings
codium --install-extension esbenp.prettier-vscode
