#!/bin/sh
echo "Installing packages"
sudo apt install -y \
    awesome \
    fish \
    redshift \
    rofi \
    slock \
    synapse \
    tmux \
    uswsusp \
    vim \
    xterm

echo "Allowing all users to use s2ram"
sudo chmod +s /usr/sbin/s2ram
