#!/usr/bin/env perl
use FindBin;
use lib "$FindBin::Bin/../.meta";
use Dotfiles qw( :ALL );

my $HERE = dir(__FILE__);


gprint "Linking emacs config dir";
symlink $HERE, "$HOME/.emacs.d";

gprint "Installing emacs plugins";
system "emacs --batch -l ~/.emacs.d/init.el"
