#!/usr/bin/env perl

use File::Basename 'dirname';
use Cwd 'realpath';
use Term::ANSIColor qw(:constants);

sub gprint {
    print GREEN, @_, RESET, "\n";
}

my $thisdir = dirname(realpath(__FILE__));
my $HOME = $ENV{"HOME"};


gprint "Linking fish config dir";
symlink $thisdir, "$HOME/.config/fish";

gprint "Disabling fish motd";
system "fish -c 'set -U fish_greeting'"