#!/usr/bin/env perl
use FindBin;
use lib "$FindBin::Bin/../.meta";
use Dotfiles qw( :ALL );

my $HERE = dir(__FILE__);


gprint "Linking fish config dir";
symlink $HERE, "$HOME/.config/fish";

gprint "Disabling fish motd";
ex "fish -c 'set -U fish_greeting'"